application: Carassius
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /.*
  script: carassius.web.main.app

libraries:
- name: jinja2
  version: latest